### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by moritzwindmann** [studio-arrenberg/quartiersdisplay-interface#3]
Use Library for apple emojis

**Comment by moritzwindmann** [comment]
Used:  https://dreamyguy.github.io/react-emojis/
and: https://github.com/IonicaBizau/emoji-dictionary

Dictionary ist leider veraltet. @j0hannr vielleicht findest du eine bessere Lösung den Namen des emojis zu bekommen

**Comment by j0hannr** [comment]
Probier das mal:

```js
function getEmojiName(emoji) {
  // Convert the emoji to its Unicode representation
  var unicode = emoji.toString();

  // Extract the name from the Unicode representation using a regular expression
  var matches = unicode.match(/^\[object UnicodeEmoji: (.*)\]$/);
  if (matches && matches.length > 1) {
    return matches[1];
  } else {
    return null;
  }
}

// Test the function
console.log(getEmojiName('🎃')); // Output: "Jack-O-Lantern"

```

Könnte sein, dass das nicht auf Linux funktioniert

**Comment by moritzwindmann** [comment]
Nein leider nicht.. 
--> null

ich habe es jetzt temporär gelöst in dem ich die alten emoji Namen mit neuen ersetze. zumindest bei denen die aktuell genutzt werden.. Ideal ist das aber offensichtlich nicht!
